# Copyright 2020-2024 Datum Technology Corporation
# All rights reserved.
#######################################################################################################################


image: python:3.11

stages:
  - test
  - build

before_script:
  - make venv

test:
  stage: test
  script:
    - make test

docs:
  stage: build
  script:
    - make build
    - make docs

