# Copyright 2020-2024 Datum Technology Corporation
# All rights reserved.
#######################################################################################################################


image: python:3.12

stages:
  - test
  - build

before_script: []

test:
  stage: test
  script:
    - make lint
    - make test

docs:
  stage: build
  script:
    - make build
    - make docs

