# Copyright 2020-2024 Datum Technology Corporation
# All rights reserved.
#######################################################################################################################


trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildAndTest
  displayName: 'Build and Test'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.11'
      addToPath: true
  - script: make venv
    displayName: 'Setup Virtual Environment and install Dependencies'
  - script: |
      make test
    displayName: 'Run tests'
  - script: |
      make build
    displayName: 'Build package'
  - script: |
      make docs
    displayName: 'Build documentation'

