# Copyright 2020-2024 Datum Technology Corporation
# All rights reserved.
#######################################################################################################################


trigger:
- '*'

pool:
  vmImage: 'ubuntu-latest'

jobs:
- job: BuildAndTest
  displayName: 'Build and Test'
  steps:
  - task: UsePythonVersion@0
    inputs:
      versionSpec: '3.12'
      addToPath: true
  - script: |
      make test
    displayName: 'Run tests'
  - script: make lint
    displayName: 'Run lint'
  - script: |
      make docs
    displayName: 'Build documentation'
  - script: |
      make build
    displayName: 'Build package'

