# Copyright 2020-2024 Datum Technology Corporation
# All rights reserved.
#######################################################################################################################


image: python:3.12

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - make test
          - make lint
          - make docs
          - make build