# Copyright 2020-2024 Datum Technology Corporation
# All rights reserved.
#######################################################################################################################


image: python:3.11

pipelines:
  default:
    - step:
        caches:
          - pip
        script:
          - make venv
          - make test
          - make build
          - make docs