# Copyright 2020-2024 Datum Technology Corporation
# All rights reserved.
#######################################################################################################################


language: python
python:
  - "3.12"
install: []
script:
  - make test
  - make lint
  - make docs
  - make build