# Copyright 2020-2024 Datum Technology Corporation
# All rights reserved.
#######################################################################################################################


language: python
python:
  - "3.11"
install:
  - make venv
script:
  - make test
  - make build
  - make docs