# Copyright 2020-2024 Datum Technology Corporation
# All rights reserved.
#######################################################################################################################


version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.12

    steps:
      - checkout

      - run:
          name: Run tests
          command: make test

      - run:
          name: Run Lint
          command: make lint

      - run:
          name: Build documentation
          command: make docs

      - run:
          name: Build package
          command: make build

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

