# Copyright 2020-2024 Datum Technology Corporation
# All rights reserved.
#######################################################################################################################


version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.11

    steps:
      - checkout

      - run:
          name: Setup Virtual Environment and Install Dependencies
          command: make venv

      - run:
          name: Run tests
          command: make test

      - run:
          name: Build package
          command: make build

      - run:
          name: Build documentation
          command: make docs

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

