# Copyright 2020-2024 Datum Technology Corporation
# All rights reserved.
#######################################################################################################################


version: 2.1

jobs:
  build:
    docker:
      - image: circleci/python:3.11

    steps:
      - checkout

      - run:
          name: Install dependencies
          command: |
            pip install -r requirements.txt
            pip install -r requirements-dev.txt

      - run:
          name: Run tests
          command: make test

      - run:
          name: Build documentation
          command: make docs

workflows:
  version: 2
  build_and_test:
    jobs:
      - build

