# Copyright 2020-2024 Datum Technology Corporation
# All rights reserved.
#######################################################################################################################


name: Python Package

on: [pull_request]

jobs:
  build:
    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.12]

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Set up Python ${{ matrix.python-version }}
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}

      - name: Lint
        run: make lint
      
      - name: Test
        run: make test

      - name: Build Package
        run: make build

      - name: Build Docs
        run: make docs

